apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-app
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - image: nginx
        name: web-app
        env:
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/var/run/secret/cloud.google.com/$APPLICATION-sa-key.json"
        - name: "PROJECT_ID"
          valueFrom:
            configMapKeyRef:
              name: project-id
              key: project-id
        - name: "ZONE"
          valueFrom:
            configMapKeyRef:
              name: web-app-zone
              key: web-app-zone
        - name: "APP_SA_EMAIL"
          valueFrom:
            configMapKeyRef:
              name: web-app-sa
              key: sa-email
        volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret:
            secretName: "web-app"